### ISSUE TITLE
Stage direction inconsistency?

### ISSUE THREAD

**Issue by vr8hub** [b-t-k/eugene-oneill_the-hairy-ape#4]
1. There is some inconsistency between when you break stage direction into its own table entry and when you keep it inline. In some cases, e.g. with the "A whole chorus of voices…" on line 248 of Scene 1, that's inline in the scans but separate in the book. However, the same type of direction a bit later, at the end of Long's speech ("There had been a gradual murmur…"), the direction is kept inline. They're both at the end of a character's dialog, but handled differently. I don't know if it matters which way it's handled, but I would say it should probably the same everywhere. (If I'm missing a reason for the difference, I apologize.)
2. A similar issue with direction before/after the Voices starting at line 300 in Scene 1. The before direction is included in the "together" class, but the after direction isn't. Shouldn't they both be in it?
3. There are other places where following direction isn't included; it causes a blank space between the text and the direction, which implies (to me) it's separate, but it really isn't. E.g., the Voices at the very end of Scene 4, "They have all piled on him…". That looks to me from the scans that it should be in the "together" class as well.

**Comment by b-t-k** [comment]
This one is a puzzler. I have my own internal logic for the choices I made, which mostly meant keeping the stage directions separate from the Voices since the chorus function is different from the actual action. It has more to do with other plays than the scans of this one. I will go through them again and  revisit the choices but am likely to leave some as is.
